<a href="https://colab.research.google.com/github/yunju-1118/EWHA/blob/main/HW1_Statistical_Programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### **Problem 1**

In [2]:
A = np.array([[1,2,5,1],[3,4,1,0]])

In [3]:
def mean_row(a):
    b = a.mean(axis=1)
    b = b.reshape(2,-1)
    return a-b

In [4]:
mean_row(A)

array([[-1.25, -0.25,  2.75, -1.25],
       [ 1.  ,  2.  , -1.  , -2.  ]])

### **Problem 2**

In [5]:
A = np.array([[1,2,5,1],[3,4,1,0]])

In [6]:
def mean_col(a):
    b = a.mean(axis=0)
    b = b.reshape(-1,4)
    return a-b

In [7]:
mean_col(A)

array([[-1. , -1. ,  2. ,  0.5],
       [ 1. ,  1. , -2. , -0.5]])

### **Problem 3**

In [8]:
A = np.array([[4.5, 3.5], [5.1, 2.3]])
B = np.array([[1],[2]])
print(A.shape, B.shape)

(2, 2) (2, 1)


In [9]:
C = np.concatenate((A,B), axis=1)
print(C, C.shape)

[[4.5 3.5 1. ]
 [5.1 2.3 2. ]] (2, 3)


### **Problem 4**

In [10]:
A = np.array([[4.5, 3.5], [5.1, 2.3]])
B = np.array([[4,3],[5,2],[1,1]])
print(A.shape, B.shape)

(2, 2) (3, 2)


In [11]:
C = np.concatenate((A,B), axis=0)
print(C, C.shape)

[[4.5 3.5]
 [5.1 2.3]
 [4.  3. ]
 [5.  2. ]
 [1.  1. ]] (5, 2)


### **Problem 5**

In [12]:
def my_function(a,b):
    mat = np.zeros([a,b])
    mat[0,:] = 1
    mat[-1,:] = 1
    mat[:,0] = 1
    mat[:,-1] = 1
    return mat

In [13]:
my_function(10,10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### **Problem 6**

In [14]:
def window(x,k):
    x = np.array(x)
    mat = np.zeros(len(x)-k+1)
    for i in range(len(mat)):
        mat[i] = x[i:i+k].mean()
    return mat

In [15]:
a = [3,5,7,2,8,10,11,65,72,81,99,100,150]
window(a,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

### **Problem 7**

#### **(a)**

In [16]:
N = np.array([[0,1,0,1,2],
              [1,3,2,1,0],
              [0,0,0,1,3]])

print(N, N.shape)

[[0 1 0 1 2]
 [1 3 2 1 0]
 [0 0 0 1 3]] (3, 5)


In [17]:
S = np.array([[157,167,130,145,170],
              [250,260,263,273,290],
              [301,120,30,100,502]])

print(S, S.shape)

[[157 167 130 145 170]
 [250 260 263 273 290]
 [301 120  30 100 502]] (3, 5)


In [18]:
SC = np.array([[1,1,1,1,1],
               [0,0,0,0,0],
               [0,0,0,0,0]])

print(SC, SC.shape)

[[1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]] (3, 5)


#### **(b)**

In [19]:
Y = np.array([[[0,157,1],[1,167,1],[0,130,1],[1,145,1],[2,170,1]],
              [[1,250,0],[3,260,0],[2,263,0],[1,273,0],[0,290,0]],
              [[0,301,0],[0,120,0],[0,30,0],[1,100,0],[3,502,0]]])


print(Y,Y.shape)

[[[  0 157   1]
  [  1 167   1]
  [  0 130   1]
  [  1 145   1]
  [  2 170   1]]

 [[  1 250   0]
  [  3 260   0]
  [  2 263   0]
  [  1 273   0]
  [  0 290   0]]

 [[  0 301   0]
  [  0 120   0]
  [  0  30   0]
  [  1 100   0]
  [  3 502   0]]] (3, 5, 3)


#### **(c)**

In [20]:
Y_new = np.stack((N,S,SC),axis=2)
print(Y_new)

[[[  0 157   1]
  [  1 167   1]
  [  0 130   1]
  [  1 145   1]
  [  2 170   1]]

 [[  1 250   0]
  [  3 260   0]
  [  2 263   0]
  [  1 273   0]
  [  0 290   0]]

 [[  0 301   0]
  [  0 120   0]
  [  0  30   0]
  [  1 100   0]
  [  3 502   0]]]


#### **(d)**

In [21]:
Y2 = np.array([[[0,1,0,1,2],[157,167,130,145,170],[1,1,1,1,1]],
               [[1,3,2,1,0],[250,260,263,273,290],[0,0,0,0,0]],
               [[0,0,0,1,3],[301,120,30,100,502],[0,0,0,0,0]]])

print(Y2, Y2.shape)

[[[  0   1   0   1   2]
  [157 167 130 145 170]
  [  1   1   1   1   1]]

 [[  1   3   2   1   0]
  [250 260 263 273 290]
  [  0   0   0   0   0]]

 [[  0   0   0   1   3]
  [301 120  30 100 502]
  [  0   0   0   0   0]]] (3, 3, 5)


#### **(e)**

In [22]:
Y2_new = np.swapaxes(Y,2,1)
print(Y2_new, Y2_new.shape)

[[[  0   1   0   1   2]
  [157 167 130 145 170]
  [  1   1   1   1   1]]

 [[  1   3   2   1   0]
  [250 260 263 273 290]
  [  0   0   0   0   0]]

 [[  0   0   0   1   3]
  [301 120  30 100 502]
  [  0   0   0   0   0]]] (3, 3, 5)


#### **(f)**

In [23]:
Y2_new2 = np.stack((N,S,SC),axis=1)
print(Y2_new2, Y2_new2.shape)

[[[  0   1   0   1   2]
  [157 167 130 145 170]
  [  1   1   1   1   1]]

 [[  1   3   2   1   0]
  [250 260 263 273 290]
  [  0   0   0   0   0]]

 [[  0   0   0   1   3]
  [301 120  30 100 502]
  [  0   0   0   0   0]]] (3, 3, 5)


### **Problem 8**

#### **(1)**

In [24]:
import pandas as pd
data = pd.read_csv('HW_1_Problem_8.csv')
data.head()

ID  Year  Income  Loss  Stock  House
0   1     1     330   164     92    105
1   1     2     340   170     99    107
2   1     3     350   176    106    109
3   1     4     360   182    113    111
4   1     5     370   188    120    113

In [25]:
data = data.sort_values(by=["ID","Year"]).reset_index(drop=True)
data.head()

ID  Year  Income  Loss  Stock  House
0   1     1     330   164     92    105
1   1     2     340   170     99    107
2   1     3     350   176    106    109
3   1     4     360   182    113    111
4   1     5     370   188    120    113

In [26]:
X = data[["Income","Loss","Stock","House"]].to_numpy().reshape(10,5,4)
print(X,X.shape)

[[[330 164  92 105]
  [340 170  99 107]
  [350 176 106 109]
  [360 182 113 111]
  [370 188 120 113]]

 [[350 172  97 108]
  [360 178 104 110]
  [370 184 111 112]
  [380 190 118 114]
  [390 196 125 116]]

 [[370 180 102 111]
  [380 186 109 113]
  [390 192 116 115]
  [400 198 123 117]
  [410 204 130 119]]

 [[390 188 107 114]
  [400 194 114 116]
  [410 200 121 118]
  [420 206 128 120]
  [430 212 135 122]]

 [[410 196 112 117]
  [420 202 119 119]
  [430 208 126 121]
  [440 214 133 123]
  [450 220 140 125]]

 [[430 204 117 120]
  [440 210 124 122]
  [450 216 131 124]
  [460 222 138 126]
  [470 228 145 128]]

 [[450 212 122 123]
  [460 218 129 125]
  [470 224 136 127]
  [480 230 143 129]
  [490 236 150 131]]

 [[470 220 127 126]
  [480 226 134 128]
  [490 232 141 130]
  [500 238 148 132]
  [510 244 155 134]]

 [[490 228 132 129]
  [500 234 139 131]
  [510 240 146 133]
  [520 246 153 135]
  [530 252 160 137]]

 [[510 236 137 132]
  [520 242 144 134]
  [530 248 151 136]
  [540 254 158 138]
  

#### **(2)**

In [27]:
Y = np.zeros((10,5,2))

for i in range(10):
    for j in range(5):
        net_asset = X[i,j,0] - X[i,j,1] + X[i,j,2]  # Income-Loss+Stock
        wealth = X[i,j,2] + X[i,j,3]    # Stock+House
        Y[i,j,0] = net_asset
        Y[i,j,1] = wealth

print(Y,Y.shape)

[[[258. 197.]
  [269. 206.]
  [280. 215.]
  [291. 224.]
  [302. 233.]]

 [[275. 205.]
  [286. 214.]
  [297. 223.]
  [308. 232.]
  [319. 241.]]

 [[292. 213.]
  [303. 222.]
  [314. 231.]
  [325. 240.]
  [336. 249.]]

 [[309. 221.]
  [320. 230.]
  [331. 239.]
  [342. 248.]
  [353. 257.]]

 [[326. 229.]
  [337. 238.]
  [348. 247.]
  [359. 256.]
  [370. 265.]]

 [[343. 237.]
  [354. 246.]
  [365. 255.]
  [376. 264.]
  [387. 273.]]

 [[360. 245.]
  [371. 254.]
  [382. 263.]
  [393. 272.]
  [404. 281.]]

 [[377. 253.]
  [388. 262.]
  [399. 271.]
  [410. 280.]
  [421. 289.]]

 [[394. 261.]
  [405. 270.]
  [416. 279.]
  [427. 288.]
  [438. 297.]]

 [[411. 269.]
  [422. 278.]
  [433. 287.]
  [444. 296.]
  [455. 305.]]] (10, 5, 2)


#### **(3)**

In [28]:
result = pd.DataFrame({
    "ID": data["ID"],
    "Year": data["Year"],
    "Net asset": Y[:,:,0].reshape(-1),
    "Wealth": Y[:,:,1].reshape(-1)
})

result.head()

ID  Year  Net asset  Wealth
0   1     1      258.0   197.0
1   1     2      269.0   206.0
2   1     3      280.0   215.0
3   1     4      291.0   224.0
4   1     5      302.0   233.0

In [29]:
result.to_csv("HW_Problem8-3.csv", index=False)

#### **(4)**

In [30]:
W = np.array([
    [1,0],
    [-1,0],
    [1,1],
    [0,1]
])

Y2 = X@W
print(Y2)

[[[258 197]
  [269 206]
  [280 215]
  [291 224]
  [302 233]]

 [[275 205]
  [286 214]
  [297 223]
  [308 232]
  [319 241]]

 [[292 213]
  [303 222]
  [314 231]
  [325 240]
  [336 249]]

 [[309 221]
  [320 230]
  [331 239]
  [342 248]
  [353 257]]

 [[326 229]
  [337 238]
  [348 247]
  [359 256]
  [370 265]]

 [[343 237]
  [354 246]
  [365 255]
  [376 264]
  [387 273]]

 [[360 245]
  [371 254]
  [382 263]
  [393 272]
  [404 281]]

 [[377 253]
  [388 262]
  [399 271]
  [410 280]
  [421 289]]

 [[394 261]
  [405 270]
  [416 279]
  [427 288]
  [438 297]]

 [[411 269]
  [422 278]
  [433 287]
  [444 296]
  [455 305]]]


### **Problem 9**

#### **(a)**

In [31]:
M = np.array([
    [500,520,540,560],
    [3.0,np.nan,2.5,2.0],
    [50,52,55,57],
    [90,100,100,110]
])

M

array([[500. , 520. , 540. , 560. ],
       [  3. ,   nan,   2.5,   2. ],
       [ 50. ,  52. ,  55. ,  57. ],
       [ 90. , 100. , 100. , 110. ]])

In [32]:
mu = np.nanmean(M,axis=1)
print(mu, mu.shape)

[530.    2.5  53.5 100. ] (4,)


In [33]:
std = np.nanstd(M,axis=1)
print(std, std.shape)

[22.36067977  0.40824829  2.6925824   7.07106781] (4,)


#### **(b)**

In [34]:
mu = mu.reshape([mu.shape[0],1])
print(mu, mu.shape)

[[530. ]
 [  2.5]
 [ 53.5]
 [100. ]] (4, 1)


In [35]:
std = std.reshape([std.shape[0],1])
print(std, std.shape)

[[22.36067977]
 [ 0.40824829]
 [ 2.6925824 ]
 [ 7.07106781]] (4, 1)


In [36]:
M_norm = (M-mu)/std
M_norm

array([[-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079],
       [ 1.22474487,         nan,  0.        , -1.22474487],
       [-1.29986737, -0.55708601,  0.55708601,  1.29986737],
       [-1.41421356,  0.        ,  0.        ,  1.41421356]])

#### **(d)**

In [37]:
M_rec = std*M_norm + mu
M_rec

array([[500. , 520. , 540. , 560. ],
       [  3. ,   nan,   2.5,   2. ],
       [ 50. ,  52. ,  55. ,  57. ],
       [ 90. , 100. , 100. , 110. ]])

In [38]:
M

array([[500. , 520. , 540. , 560. ],
       [  3. ,   nan,   2.5,   2. ],
       [ 50. ,  52. ,  55. ,  57. ],
       [ 90. , 100. , 100. , 110. ]])

### **Problem 10**

#### **(a)**

In [39]:
X=np.array([
    [160,55,170,65],
    [165,60,175,70],
    [170,58,180,72]
])

print(X,X.shape)

[[160  55 170  65]
 [165  60 175  70]
 [170  58 180  72]] (3, 4)


In [40]:
W = np.array([[0.5,0.1],[0.2,0.3],[0.4,0.2],[0.1,0.4]])
print(W,W.shape)

[[0.5 0.1]
 [0.2 0.3]
 [0.4 0.2]
 [0.1 0.4]] (4, 2)


In [41]:
c = np.array([1.0,2.0])
print(c,c.shape)

[1. 2.] (2,)


In [42]:
y_hat = X@W+c
print(y_hat, y_hat.shape)

[[166.5  94.5]
 [172.5  99.5]
 [176.8 101.2]] (3, 2)


#### **(b)**

In [43]:
ones = np.array([[1],[1],[1]])
X_a = np.concatenate((ones,X),axis=1)
print(X_a, X_a.shape)

[[  1 160  55 170  65]
 [  1 165  60 175  70]
 [  1 170  58 180  72]] (3, 5)


In [44]:
c = c.reshape(-1,2)

In [45]:
W_a = np.concatenate((c,W),axis=0)
print(W_a, W_a.shape)

[[1.  2. ]
 [0.5 0.1]
 [0.2 0.3]
 [0.4 0.2]
 [0.1 0.4]] (5, 2)


In [46]:
y_hat2 = X_a@W_a
print(y_hat2, y_hat2.shape)

[[166.5  94.5]
 [172.5  99.5]
 [176.8 101.2]] (3, 2)


### **Problem 11**

In [47]:
A = np.array([[1,2,3],[4,5,6]])
b_row = np.array([10,20,30])
b_col = np.array([[10],[100]])
E = np.array([[1],[2]])
F = np.array([[10,20,30]])

#### **(a)** - possible

In [48]:
A+b_row

array([[11, 22, 33],
       [14, 25, 36]])

#### **(b)** - possible

In [49]:
A+b_col

array([[ 11,  12,  13],
       [104, 105, 106]])

#### **(c)** - Possible

In [50]:
E+F

array([[11, 21, 31],
       [12, 22, 32]])

#### **(d)** - not possible

In [51]:
d = np.array([10,20])
A+d

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 